function Whitepaper() {
    return (   
        <div className="whitepaper" id="whitepaper">
            <div className="whitepaper-content">
                <img className="whitepaper-bg" src="/images/whitepaper/black-bg.png"></img>
                <div className="whitepaper-title"> <div>WHITE</div> <div className="pink"> PAPER </div></div>
                <div className="whitepaper-text">
                We are building a blockchain-based social networking marketplace platform that uses NFTs and crypto currencies.
                <br></br><br></br>
                There will be no advertising and no algorithm for your feed, giving content creators the complete freedom to own and monetize their own content. We will not collect or store any data from our platform that could be used for advertising, and we will never sell any data. We will build with React first, followed by the Android version, and last but not least the Apple version.
                <br></br><br></br>
                Fuck social media. This is a social networking revolution.
                <br></br><br></br>
                The NFT project is a limited collection of 10k. Each NFT grants the holder a premium subscription as well as an advisory position on the project. The mint will be progressively priced. The thinking behind this is to allow people to take profits early in the project if they choose to do so. The first 1k in the collection is now open to the public at a price of .1 ETH. There is also a built-in WL function if we choose to implement it. There will be 10 phases in total, each having 1k NFTs. Each phase will also have a single one-of-one piece hidden in the collection. The ETH price will increase by .1 for each phase, resulting in the last phase being 1 ETH. There are also 10 one-of-ones that are available to mint for 1 ETH each.  The community will choose when to release each phase of minting. The complete art for the normal collection will be revealed once the project mints out.
                <br></br><br></br>
                80% of all mint revenue will be put into our community wallet. Before implementing new ideas or decisions on how to use funds in the community wallet, everything will be put to a vote, similar to the way a DAO works. The founder will get 20% of the mint. The regular NFT in the collection will work similar to how the House of Representatives works, and the one-of-one holders will act more as the Senate. The founder will get the final say in all decisions. There will be no royalties for this collection.
                <br></br><br></br>
                The collection also includes 20 one-of-one pieces with extra utility, such as increasing your platform revenue share to .075%, while the normal collection gets .00035%. In total, 50% of all revenue generated by the platform will go into the community wallet to be divided among the content creators, the founder will get 6%, and 1% will be given to charity, leaving 38% to be reinvested into the growth of the platform.
                <br></br><br></br>
                Only NFT holders will have access to the beta versions of the platform, and they will get to be a part of designing it as well.
                </div> 
            </div>
        </div>

    )
}    
export default Whitepaper;